script: rake spec
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm:
      - 1.9.3
      - 2.0.0
      - rbx-2.1.1
      - jruby-head
      - ruby-head
