script: rake spec
rvm:
  - 2.2
  - 2.3
  - 2.4.0-preview3
  - ruby-head
  - jruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm:
      - 2.4.0-preview3
      - jruby-head
      - ruby-head
      - rbx-2.1.1
